import '../models/campus_location_model.dart';
import '../models/cart_item_model.dart';
import '../models/menu_item_model.dart';
import '../models/order_model.dart';
import '../models/restaurant_model.dart';
import '../models/user_model.dart';
import '../models/wallet_transaction_model.dart';

/// In-memory mock data for MVP.
///
/// TODO: Replace with Firestore repositories before production.
/// TODO: Never store payment secrets or plaintext passwords client-side.
class MockDataService {
  MockDataService._();

  static final UserModel currentUser = UserModel(
    id: 'u001',
    name: 'Ahmed',
    email: 'ahmed@udst.edu.qa',
    phone: '+974 55xx xxxx',
    universityId: '60102677',
    role: UserRole.student,
    walletBalance: 47.50,
    loyaltyPoints: 1240,
    dietaryPreferences: ['Vegetarian', 'No Nuts'],
  );

  static final List<RestaurantModel> restaurants = [
    const RestaurantModel(
      id: 'r001',
      name: 'Tim Hortons',
      category: 'Coffee & Bakery',
      building: 'B3',
      description: 'Canadian coffeehouse & baked goods',
      rating: 4.8,
      reviewCount: 289,
      deliveryTimeMin: 8,
      minOrder: 10.0,
      isOpen: true,
      offersDelivery: true,
      offersPickup: true,
      discountPercent: 30.0,
      campusX: 0.18,
      campusY: 0.22,
    ),
    const RestaurantModel(
      id: 'r002',
      name: 'Oakberry',
      category: 'Açaí & Healthy',
      building: 'B3',
      description: 'Fresh açaí bowls and healthy snacks',
      rating: 4.9,
      reviewCount: 312,
      deliveryTimeMin: 5,
      minOrder: 18.0,
      isOpen: true,
      offersDelivery: true,
      offersPickup: true,
      campusX: 0.22,
      campusY: 0.18,
    ),
    const RestaurantModel(
      id: 'r003',
      name: 'Edge Cafe',
      category: 'Café',
      building: 'B9',
      description: 'Specialty coffee & light bites',
      rating: 4.6,
      reviewCount: 156,
      deliveryTimeMin: 15,
      minOrder: 12.0,
      isOpen: true,
      offersDelivery: true,
      offersPickup: true,
      campusX: 0.55,
      campusY: 0.20,
    ),
    const RestaurantModel(
      id: 'r004',
      name: 'Caribou Coffee',
      category: 'Coffee',
      building: 'E4',
      description: 'Coffee & espresso drinks',
      rating: 4.5,
      reviewCount: 98,
      deliveryTimeMin: 2,
      minOrder: 8.0,
      isOpen: true,
      offersDelivery: true,
      offersPickup: true,
      campusX: 0.42,
      campusY: 0.55,
    ),
    const RestaurantModel(
      id: 'r005',
      name: 'JamKai',
      category: 'Asian Fusion',
      building: 'B20',
      description: 'Asian bowls, noodles & bubble tea',
      rating: 4.7,
      reviewCount: 201,
      deliveryTimeMin: 12,
      minOrder: 20.0,
      isOpen: true,
      offersDelivery: true,
      offersPickup: true,
      campusX: 0.40,
      campusY: 0.75,
    ),
    const RestaurantModel(
      id: 'r006',
      name: 'Bold Café',
      category: 'Café',
      building: 'Atrium 5',
      description: 'Campus café with sandwiches & salads',
      rating: 4.4,
      reviewCount: 134,
      deliveryTimeMin: 8,
      minOrder: 15.0,
      isOpen: true,
      offersDelivery: true,
      offersPickup: true,
      campusX: 0.50,
      campusY: 0.60,
    ),
    const RestaurantModel(
      id: 'r007',
      name: 'L\'Hardy',
      category: 'Qatari Cuisine',
      building: 'B12',
      description: 'Traditional Qatari dishes',
      rating: 4.7,
      reviewCount: 178,
      deliveryTimeMin: 18,
      minOrder: 25.0,
      isOpen: true,
      offersDelivery: false,
      offersPickup: true,
      campusX: 0.65,
      campusY: 0.35,
    ),
    const RestaurantModel(
      id: 'r008',
      name: 'Ennabi 92',
      category: 'Qatari Cuisine',
      building: 'B4',
      description: 'Authentic local flavors',
      rating: 4.7,
      reviewCount: 145,
      deliveryTimeMin: 14,
      minOrder: 22.0,
      isOpen: true,
      offersDelivery: false,
      offersPickup: true,
      campusX: 0.48,
      campusY: 0.68,
    ),
  ];

  static List<MenuItemModel> menuForRestaurant(String restaurantId) {
    return _menuItems.where((m) => m.restaurantId == restaurantId).toList();
  }

  static final List<MenuItemModel> _menuItems = [
    // Tim Hortons
    const MenuItemModel(
      id: 'm001',
      restaurantId: 'r001',
      name: 'Original Blend Coffee',
      description: 'Medium roast, freshly brewed',
      price: 10.50,
      category: 'Coffee',
      isBestseller: true,
    ),
    const MenuItemModel(
      id: 'm002',
      restaurantId: 'r001',
      name: 'Iced Capp',
      description: 'Creamy blended iced coffee',
      price: 14.00,
      category: 'Cold Drinks',
      isPopular: true,
    ),
    const MenuItemModel(
      id: 'm003',
      restaurantId: 'r001',
      name: 'Boston Cream Donut',
      description: 'Custard filled with chocolate glaze',
      price: 7.00,
      category: 'Bakery',
      isBestseller: true,
    ),
    const MenuItemModel(
      id: 'm004',
      restaurantId: 'r001',
      name: 'Timbits (10 Pack)',
      description: 'Assorted bite-sized donuts',
      price: 12.00,
      category: 'Bakery',
    ),
    // Oakberry
    const MenuItemModel(
      id: 'm005',
      restaurantId: 'r002',
      name: 'Original Açaí Bowl',
      description: 'Açaí, granola, banana & honey',
      price: 28.00,
      category: 'Bowls',
      isBestseller: true,
    ),
    const MenuItemModel(
      id: 'm006',
      restaurantId: 'r002',
      name: 'Protein Açaí Bowl',
      description: 'Açaí with protein & mixed berries',
      price: 32.00,
      category: 'Bowls',
      isPopular: true,
    ),
    const MenuItemModel(
      id: 'm007',
      restaurantId: 'r002',
      name: 'Green Detox Smoothie',
      description: 'Spinach, apple, ginger & lemon',
      price: 22.00,
      category: 'Drinks',
    ),
    // Edge Cafe
    const MenuItemModel(
      id: 'm008',
      restaurantId: 'r003',
      name: 'Spanish Latte',
      description: 'Espresso with sweet condensed milk',
      price: 18.00,
      category: 'Coffee',
      isBestseller: true,
    ),
    const MenuItemModel(
      id: 'm009',
      restaurantId: 'r003',
      name: 'Avocado Toast',
      description: 'Sourdough, avocado, poached egg',
      price: 24.00,
      category: 'Food',
      isNew: true,
    ),
    const MenuItemModel(
      id: 'm010',
      restaurantId: 'r003',
      name: 'Croissant',
      description: 'Butter croissant, freshly baked',
      price: 9.00,
      category: 'Bakery',
    ),
    // Caribou Coffee
    const MenuItemModel(
      id: 'm011',
      restaurantId: 'r004',
      name: 'Campfire Mocha',
      description: 'Chocolate, espresso & toasted marshmallow',
      price: 20.00,
      category: 'Coffee',
      isPopular: true,
    ),
    const MenuItemModel(
      id: 'm012',
      restaurantId: 'r004',
      name: 'Iced Cold Press',
      description: 'Slow-steeped cold brew',
      price: 16.00,
      category: 'Cold Drinks',
    ),
    // JamKai
    const MenuItemModel(
      id: 'm013',
      restaurantId: 'r005',
      name: 'Teriyaki Chicken Bowl',
      description: 'Rice, teriyaki chicken & veggies',
      price: 26.00,
      category: 'Bowls',
      isBestseller: true,
    ),
    const MenuItemModel(
      id: 'm014',
      restaurantId: 'r005',
      name: 'Ramen Noodles',
      description: 'Miso broth, noodles, egg & corn',
      price: 30.00,
      category: 'Noodles',
    ),
    const MenuItemModel(
      id: 'm015',
      restaurantId: 'r005',
      name: 'Bubble Tea',
      description: 'Milk tea with tapioca pearls',
      price: 16.00,
      category: 'Drinks',
      isPopular: true,
    ),
    // Bold Café
    const MenuItemModel(
      id: 'm016',
      restaurantId: 'r006',
      name: 'Chicken Panini',
      description: 'Grilled chicken, mozzarella & pesto',
      price: 22.00,
      category: 'Food',
      isBestseller: true,
    ),
    const MenuItemModel(
      id: 'm017',
      restaurantId: 'r006',
      name: 'Caesar Salad',
      description: 'Romaine, croutons & parmesan',
      price: 19.00,
      category: 'Healthy',
    ),
    // L'Hardy
    const MenuItemModel(
      id: 'm018',
      restaurantId: 'r007',
      name: 'Machboos',
      description: 'Traditional spiced rice with chicken',
      price: 35.00,
      category: 'Mains',
      isBestseller: true,
    ),
    const MenuItemModel(
      id: 'm019',
      restaurantId: 'r007',
      name: 'Harees',
      description: 'Wheat & meat porridge',
      price: 28.00,
      category: 'Mains',
    ),
  ];

  static final List<OrderModel> orders = [
    OrderModel(
      id: 'o001',
      userId: 'u001',
      restaurantId: 'r002',
      restaurantName: 'Oakberry',
      items: [
        CartItemModel(
          id: 'ci001',
          item: menuForRestaurant('r002').first,
          quantity: 1,
        ),
      ],
      subtotal: 28.00,
      deliveryFee: 2.50,
      total: 30.50,
      status: OrderStatus.delivering,
      deliveryType: DeliveryType.delivery,
      driverName: 'Khalid',
      driverPhone: '+974 66xx xxxx',
      createdAt: DateTime.now().subtract(const Duration(minutes: 18)),
      estimatedDelivery: DateTime.now().add(const Duration(minutes: 7)),
      timeline: [
        OrderTimelineStep(
          label: 'Order Placed',
          timestamp: DateTime.now().subtract(const Duration(minutes: 18)),
          isComplete: true,
        ),
        OrderTimelineStep(
          label: 'Preparing',
          timestamp: DateTime.now().subtract(const Duration(minutes: 14)),
          isComplete: true,
        ),
        OrderTimelineStep(
          label: 'On the Way',
          timestamp: DateTime.now().subtract(const Duration(minutes: 4)),
          isComplete: true,
        ),
        const OrderTimelineStep(label: 'Delivered', isComplete: false),
      ],
    ),
    OrderModel(
      id: 'o002',
      userId: 'u001',
      restaurantId: 'r001',
      restaurantName: 'Tim Hortons',
      items: [
        CartItemModel(
          id: 'ci002',
          item: menuForRestaurant('r001').firstWhere((m) => m.id == 'm001'),
          quantity: 2,
        ),
        CartItemModel(
          id: 'ci003',
          item: menuForRestaurant('r001').firstWhere((m) => m.id == 'm003'),
          quantity: 1,
        ),
      ],
      subtotal: 28.00,
      deliveryFee: 0.0,
      total: 28.00,
      status: OrderStatus.delivered,
      deliveryType: DeliveryType.pickup,
      createdAt: DateTime.now().subtract(const Duration(days: 1, hours: 2)),
      estimatedDelivery: DateTime.now().subtract(const Duration(days: 1, hours: 1)),
      timeline: [
        OrderTimelineStep(
          label: 'Order Placed',
          timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 2)),
          isComplete: true,
        ),
        OrderTimelineStep(
          label: 'Preparing',
          timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 1, minutes: 45)),
          isComplete: true,
        ),
        OrderTimelineStep(
          label: 'Ready for Pickup',
          timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 1, minutes: 15)),
          isComplete: true,
        ),
        OrderTimelineStep(
          label: 'Picked Up',
          timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 1)),
          isComplete: true,
        ),
      ],
    ),
  ];

  static final List<WalletTransactionModel> walletTransactions = [
    WalletTransactionModel(
      id: 't001',
      userId: 'u001',
      amount: 50.00,
      type: TransactionType.topUp,
      reference: 'NOQ-782910',
      description: 'Top-up via Noqoody',
      timestamp: DateTime.now().subtract(const Duration(days: 2)),
    ),
    WalletTransactionModel(
      id: 't002',
      userId: 'u001',
      amount: 28.00,
      type: TransactionType.payment,
      reference: 'ORD-o002',
      description: 'Tim Hortons — Pickup',
      timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 2)),
    ),
    WalletTransactionModel(
      id: 't003',
      userId: 'u001',
      amount: 30.50,
      type: TransactionType.payment,
      reference: 'ORD-o001',
      description: 'Oakberry — Delivery',
      timestamp: DateTime.now().subtract(const Duration(minutes: 18)),
    ),
    WalletTransactionModel(
      id: 't004',
      userId: 'u001',
      amount: 25.50,
      type: TransactionType.topUp,
      reference: 'NOQ-119283',
      description: 'Top-up via Noqoody',
      timestamp: DateTime.now().subtract(const Duration(days: 7)),
    ),
  ];

  /// Stylized UDST campus blocks for the custom map painter.
  /// Coordinates are normalized 0.0 - 1.0 relative to map bounds.
  static final List<CampusLocationModel> campusLocations = [
    // Restaurant / Cafe locations
    const CampusLocationModel(
      id: 'loc_r001',
      label: 'B3',
      fullName: 'Building 3 — Tim Hortons, Oakberry',
      type: CampusLocationType.restaurant,
      x: 0.18,
      y: 0.20,
      width: 0.10,
      height: 0.12,
    ),
    const CampusLocationModel(
      id: 'loc_r003',
      label: 'B9',
      fullName: 'Building 9 — Edge Cafe',
      type: CampusLocationType.restaurant,
      x: 0.52,
      y: 0.18,
      width: 0.08,
      height: 0.10,
    ),
    const CampusLocationModel(
      id: 'loc_r005',
      label: 'B20',
      fullName: 'Building 20 — JamKai',
      type: CampusLocationType.restaurant,
      x: 0.36,
      y: 0.72,
      width: 0.10,
      height: 0.10,
    ),
    const CampusLocationModel(
      id: 'loc_r004',
      label: 'E4',
      fullName: 'E4 Courtyard — Caribou Coffee',
      type: CampusLocationType.restaurant,
      x: 0.40,
      y: 0.52,
      width: 0.08,
      height: 0.08,
    ),
    const CampusLocationModel(
      id: 'loc_r006',
      label: 'A5',
      fullName: 'Atrium 5 — Bold Café',
      type: CampusLocationType.restaurant,
      x: 0.50,
      y: 0.56,
      width: 0.08,
      height: 0.08,
    ),
    const CampusLocationModel(
      id: 'loc_r007',
      label: 'B12',
      fullName: 'Building 12 — L\'Hardy',
      type: CampusLocationType.restaurant,
      x: 0.62,
      y: 0.32,
      width: 0.08,
      height: 0.10,
    ),
    const CampusLocationModel(
      id: 'loc_r008',
      label: 'B4',
      fullName: 'Building 4 — Ennabi 92',
      type: CampusLocationType.restaurant,
      x: 0.46,
      y: 0.66,
      width: 0.08,
      height: 0.08,
    ),
    // Academic buildings
    const CampusLocationModel(
      id: 'loc_b10',
      label: 'B10',
      fullName: 'Building 10 — College of Computing & IT',
      type: CampusLocationType.academic,
      x: 0.28,
      y: 0.42,
      width: 0.06,
      height: 0.12,
    ),
    const CampusLocationModel(
      id: 'loc_b08',
      label: 'B8',
      fullName: 'Building 8 — College of Engineering & Technology',
      type: CampusLocationType.academic,
      x: 0.34,
      y: 0.48,
      width: 0.08,
      height: 0.10,
    ),
    const CampusLocationModel(
      id: 'loc_b13',
      label: 'B13',
      fullName: 'Building 13 — Student Central Services',
      type: CampusLocationType.facility,
      x: 0.46,
      y: 0.40,
      width: 0.08,
      height: 0.10,
    ),
    const CampusLocationModel(
      id: 'loc_b14',
      label: 'B14',
      fullName: 'Building 14 — Library',
      type: CampusLocationType.facility,
      x: 0.50,
      y: 0.48,
      width: 0.06,
      height: 0.08,
    ),
    const CampusLocationModel(
      id: 'loc_b00',
      label: '00',
      fullName: 'Obelisk',
      type: CampusLocationType.facility,
      x: 0.24,
      y: 0.64,
      width: 0.04,
      height: 0.04,
    ),
    // Sports / open areas
    const CampusLocationModel(
      id: 'loc_e17',
      label: 'E17',
      fullName: 'Event Park / Football Field',
      type: CampusLocationType.facility,
      x: 0.58,
      y: 0.06,
      width: 0.16,
      height: 0.10,
    ),
  ];
}
